language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements-dev.txt
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script: 
  PYTHONPATH=.:$PYTHONPATH py.test --cov opentaxii
#  coverage run --source=opentaxii setup.py test
after_success:
  coveralls
