[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-module = true
ignore-nested-functions = true
ignore-nested-classes = true
ignore-private = true
ignore-semiprivate = true
omit-covered-files = true
verbose = 0
exclude = ["tests"]

[tool.mypy]
plugins = ["sqlmypy"]

ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
follow_imports = "silent"

files = [
    "opentaxii/",
    "tests/",
]

exclude = """
(?x)(
    ^opentaxii/persistence/sqldb/api\\.py$
    | ^opentaxii/taxii/.+
    | ^opentaxii/utils\\.py$
    | ^opentaxii/common/entities\\.py$
)
"""
